### ISSUE TITLE
gb2260.get()接口返回值问题

### ISSUE THREAD

**Issue by ulyssess** [cn/GB2260.py#7]
你好，
   在使用的过程中发现get()接口在遇到不正确的区划编码时会raise，可不可以做成和search一样，区划编码不存在的时候就返回None呢？

**Comment by tonyseek** [comment]
当前版本认为 `get` 接口必须接受确定和有效的区划编码，所以针对无效编码抛出 `ValueError` 异常。这个行为符合 Python 中 `ValueError` 的语义和使用习惯，所以没有更改的计划。

未来版本会跟随 https://github.com/cn/GB2260/blob/develop/spec.md ，如有建议欢迎到 https://gitter.im/cn/GB2260 参与 spec 的讨论。
